language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: DeuJ95OE2y234kBp5UQr2Z+FcstbQ8Iv9bUkBtwML0BTLJw/3ZNU50KzGJT7LWauel2v47lOegOVDyL6LHpOWB8Rq8g2BDKVy0SAOQMcFLg70/bFHsk8gVnlBW64M5MuTQZ5bcJJXt1CMeUHlrn3dBfKaV5VZ7Wp0dPDcaeAwrlpzfE/VtcVVKrTy94pAQwlxX6DYvSaZ0gX7Z5pCXcxwXVsDidayYKDGYDAgUNygKjOnbkknVTOxLpHxNdTdvxn6PaNsEg7wa2fmdeogZ4Nv1d/gaz3cLcLS44zAYWGe3/wmfF6g6uyIKutEXRw/8EouKQnTNtjx86mhxZAhG1dqzk+D9L2ZD1lGSfk+zaT6vUD+uuSJNYo9jFDKeHRv8GhX3kFJSc94vBfjiT1zYmEjgMV0oa/8JCXKNcGNa7ele3yUFjJIhplBA3++rLkg6zZ7x0W+MgBJK0tDb0fq0GmoXr+0xTTrPqPfd4JW18QBAzRDAPfPbQ/XAeNUlkoT/M6RfUktUkM0dzOD0ALjkHmn3bSY4YGVaAAA+umAdr3KjcDxGlXPF7AhCXhBflYToVOZCYcHj+BpG4ki/1GVxHfx7kAiZdQjsRcmOJ+sVOXMa1L++URSO+ITr3T8f7vlnvkzjjQSG1AmF2FGsJTB7TbjL2fBFgWb4+fXkhb6hoUqCU=
  app: java-ci-app