language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: CeZnXr/onbuu8wiEblA9K26HHdoxxkHrdsuB2TDho5GAPniIhR2sU+fP/h/LBqyStXvDLuJ8D8p/q5yfxhsL4Uvo/1GfTmxSPSppnMwt5bTjzIULPdStVM43GNuU22j/MF69UgTLsx+OXMySIIAJJNY4yzsU/G3Uy1wORZBHuYtVKIDcbwPzBlFwHaKicJITCzTkIegH79PoK/9FM+6MM4OKtNGit/XQLGn7ZqLXl1acBYcPXZ3DMM9txIb/WkA/6sg9+WxHKhOBD66gF3+JjUaBWftlppH/3w1/8rhwZOKXinZxDPxjvfFNqpsX6S9QQHQ97qwcVG4gLFNGet+1cSfSQVuo7KLqh1Uh3C7Csj+HL4Zjuaia5DMqS1GAwDLrIsVQgPTSgoNa41YuG/Qb2Z7yH+NnijrXWhXEE0zgZFiclpkiWEEqRvKO/22CPUJjKUTS6g0Tg8ZOdOnsd1ioXIFDi5za7jgtMw/S9TY9Wq2p1VYga9yqqitnvbSJcJQQVK5XSGj1MAJ7NdbVPJDsbiYTg28j9r+r00gG5WEHSk+3fYP/QVv2Z91r1ASq6JNIbhNIAnl6iJ25ojMd5i3rB9t5hkrVQmRN1dy8Wy5GRD3/ooKPImAZUzCHxMvpX+gv20/c6KoJRhXfXqmQx9kNnTcUpQlc95cdaycg0bWlMAY=
  app: java-ci-app